### ISSUE TITLE
Backend service creation request - OnBoard Stats

### ISSUE THREAD

**Issue by LimesKey** [hackclub/infra#83]
Desired service name: [Prometheus](https://hub.docker.com/r/prom/prometheus) and [OnBoard Grant Aggregator](onboard-grant-aggregator) running in Docker containers. OnBoard Grant Aggregator would require a port exposed, I used `8521` for my testing. 

Prometheus would need `prometheus.yml` similar to this,
```yml
  - job_name: 'onboard grants'
    scrape_interval: 5m
    scrape_timeout: 5m
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.100:8521']
 ```

In a later pull request, I'd need Grafana access for https://grafana.limeskey.com/onboard
